blank_issues_enabled: false
contact_links:
  - name: FAWESchematicCloud Discord
    url: https://discord.onelitefeather.net
    about: If you are having issues with timings or have other minor issues, come ask us on our Discord server!